routes/web.php
<?php

$baseAdminUrl = config('octa.admin_url');

Route::middleware(['web'])->prefix($baseAdminUrl)->namespace('Lixir')->name('admin.')->group(function () {
    // login route
    Route::get('login', [\Lixir\System\Controllers\LoginController::class, 'loginForm'])->name('login');
    Route::post('login', [\Lixir\System\Controllers\LoginController::class, 'login'])->name('login.post');

    // password resets
    Route::get('password/reset', [\Lixir\System\Controllers\ForgotPasswordController::class, 'linkRequestForm'])->name('password.request');
    Route::post('password/email', [\Lixir\System\Controllers\ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');
    Route::get('password/reset/{token}', [\Lixir\System\Controllers\ResetPasswordController::class, 'showResetForm'])->name('password.reset');
    Route::post('password/reset', [\Lixir\System\Controllers\ResetPasswordController::class, 'reset'])->name('password.update');

    // logout
    Route::post('logout', [\Lixir\System\Controllers\LoginController::class, 'logout'])->name('logout');
});

Route::middleware(['web', 'admin.auth:admin', 'permission'])->prefix($baseAdminUrl)->namespace('Lixir')->name('admin.')->group(function () {
    Route::get('', [\Lixir\System\Controllers\DashboardController::class, 'index'])->name('dashboard');
    Route::get('configuration', 'System\Controllers\ConfigurationController@index')->name('configuration.index');
    Route::post('configuration', [\Lixir\System\Controllers\ConfigurationController::class, 'store'])->name('configuration.store');
    Route::post('attribute/upload', [\Lixir\Catalog\Controllers\AttributeController::class, 'upload'])->name('attribute.upload');
    Route::post('admin-user-image', [\Lixir\User\Controllers\AdminUserController::class, 'upload'])->name('admin-user-image-upload');
    Route::post('variation/{product}/create-variation', [\Lixir\Catalog\Controllers\ProductController::class, 'createVariation'])->name('product.create.variation');
    Route::post('variation/{product}/save-variation', [\Lixir\Catalog\Controllers\ProductController::class, 'saveVariation'])->name('product.save.variation');
    Route::delete('variation/{product}', [\Lixir\Catalog\Controllers\ProductController::class, 'destroyVariation'])->name('product.destroy.variation');
    Route::post('product-image/{product}/upload', [\Lixir\Catalog\Controllers\ProductController::class, 'upload'])->name('product.image.upload');
    Route::delete('product-image/{productImage}', [\Lixir\Catalog\Controllers\ProductController::class, 'destroyImage'])->name('product.image.destroy');
    Route::get('order/{order}', [\Lixir\Order\Controllers\OrderController::class, 'show'])->name('order.show');
    Route::post('order-change-status/{order}', [\Lixir\Order\Controllers\OrderController::class, 'changeStatus'])->name('order.change-status');
    Route::post('save-order-track-code/{order}', [\Lixir\Order\Controllers\OrderController::class, 'saveTrackCode'])->name('order.save.track.code');
    Route::get('order-download-invoice/{order}', [\Lixir\Order\Controllers\OrderController::class, 'downloadInvoice'])->name('order.download.invoice');
    Route::get('order-email-invoice/{order}', [\Lixir\Order\Controllers\OrderController::class, 'emailInvoice'])->name('order.email.invoice');
    Route::get('order-shipping-label/{order}', [\Lixir\Order\Controllers\OrderController::class, 'generateShippingLabel'])->name('order.shipping.label');
    Route::resource('admin-user', User\Controllers\AdminUserController::class);
    Route::resource('attribute', Catalog\Controllers\AttributeController::class);
    Route::resource('category', Catalog\Controllers\CategoryController::class);
    Route::resource('currency', System\Controllers\CurrencyController::class);
    Route::resource('language', System\Controllers\LanguageController::class);
    Route::resource('order', Order\Controllers\OrderController::class)->only(['index']);
    Route::resource('order-status', Order\Controllers\OrderStatusController::class);
    Route::resource('menu-group', Cms\Controllers\MenuGroupController::class);
    Route::resource('page', Cms\Controllers\PageController::class);
    Route::resource('property', Catalog\Controllers\PropertyController::class);
    Route::resource('product', Catalog\Controllers\ProductController::class);
    Route::resource('role', System\Controllers\RoleController::class);
    Route::resource('state', System\Controllers\StateController::class);
    Route::resource('user-group', User\Controllers\UserGroupController::class);
    Route::resource('tax-group', System\Controllers\TaxGroupController::class);
    Route::resource('tax-rate', System\Controllers\TaxRateController::class);
    Route::get('promotion-code', Promotion\Controllers\PromotionCode\TableController::class)->name('promotion.code.table');
    Route::get('promotion-code-edit/{promotionCode?}', Promotion\Controllers\PromotionCode\EditController::class)->name('promotion.code.edit');
    Route::post('promotion-code-save/{promotionCode?}', Promotion\Controllers\PromotionCode\SaveController::class)->name('promotion.code.save');
    Route::delete('promotion-code/{promotionCode}', Promotion\Controllers\PromotionCode\DestroyController::class)->name('promotion.code.destroy');
});

resources/views/breadcrumb/index.blade.php
<div class="mt-1 ml-1">
    <a-breadcrumb>
        @if(isset($breadcrumb->parents) && $breadcrumb->parents->count() >0)
            @foreach($breadcrumb->parents as $parentBreadcrumb)
                    
                <a-breadcrumb-item>
                    <a href="{{ route($parentBreadcrumb->route) }}">
                        {{ __($parentBreadcrumb->label) }}
                    </a>
                </a-breadcrumb-item>
            
            @endforeach
        @endif
        
        <a-breadcrumb-item>{{ __($breadcrumb->label) }}</a-breadcrumb-item>
    </a-breadcrumb>
</div>

resources/views/catalog/property/create.blade.php
@extends('lixir::layouts.app')

@section('meta_title')
    {{ __('lixir::catalog.property.create.title') }}: Lixir E-Commerce Admin Dashboard
@endsection

@section('page_title')
    {{ __('lixir::catalog.property.create.title') }}
@endsection

@section('content')
<a-row type="flex">
    <a-col :span="24">
        <property-save base-url="{{ asset(config('lixir.admin_url')) }}" inline-template>
        <div>
            <a-form
                :form="propertyForm"
                method="post"
                action="{{ route('admin.property.store') }}"
                @submit="handleSubmit"
            >
                @csrf

                <a-tabs tabbar-gutter="15" tab-position="left" default-active-key="catalog.property.info">
                @foreach ($tabs as $tab)
                    <a-tab-pane :force-render="true" tab="{{ $tab->label() }}" key="{{ $tab->key() }}">
                        @php
                            $path = $tab->view();
                        @endphp
                        @include($path)
                    </a-tab-pane>
                @endforeach
                </a-tabs>

                <a-form-item>
                    <a-button
                        type="primary"
                        html-type="submit"
                    >
                        {{ __('lixir::system.btn.save') }}
                    </a-button>

                    <a-button
                        class="ml-1"
                        type="default"
                        v-on:click.prevent="cancelProperty"
                    >
                        {{ __('lixir::system.btn.cancel') }}
                    </a-button>
                </a-form-item>
            </a-form>
            </div>
        </property-save>
    </a-col>
</a-row>
@endsection

resources/views/catalog/property/edit.blade.php
@extends('lixir::layouts.app')

@section('meta_title')
    {{ __('lixir::catalog.property.edit.title') }}: Lixir E-Commerce Admin Dashboard
@endsection

@section('page_title')
    {{ __('lixir::catalog.property.edit.title') }}
@endsection

@section('content')
<a-row type="flex" justify="center">
    <a-col :span="24">
        <property-save
            base-url="{{ asset(config('lixir.admin_url')) }}"
            :property="{{ $property }}" inline-template>
        <div>
            <a-form
                :form="propertyForm"
                method="post"
                action="{{ route('admin.property.update', $property->id) }}"
                @submit="handleSubmit"
            >
                @csrf
                @method('put')

                <a-tabs tabbar-gutter="15" tab-position="left" default-active-key="catalog.property.info">
                @foreach ($tabs as $tab)
                    <a-tab-pane :force-render="true" tab="{{ $tab->label() }}" key="{{ $tab->key() }}">
                        @php
                            $path = $tab->view();
                        @endphp
                        @include($path)
                    </a-tab-pane>
                @endforeach
                </a-tabs>

                <a-form-item>
                    <a-button
                        type="primary"
                        html-type="submit"
                    >
                        {{ __('lixir::system.btn.save') }}
                    </a-button>

                    <a-button
                        class="ml-1"
                        type="default"
                        v-on:click.prevent="cancelProperty"
                    >
                        {{ __('lixir::system.btn.cancel') }}
                    </a-button>
                </a-form-item>
            </a-form>
            </div>
        </property-save>
    </a-col>
</a-row>
@endsection

resources/views/catalog/property/index.blade.php
@extends('lixir::layouts.app')

@section('meta_title')
    {{ __('lixir::catalog.property.index.title') }}: Lixir E-Commerce Admin Dashboard
@endsection

@section('page_title')
    {{ __('lixir::catalog.property.index.title') }}
@endsection

@section('content')
<a-row type="flex" class="mb-1" justify="end">
    <a-col>
        <a
            href="{{ route('admin.property.create') }}"
            class="ant-btn ant-btn-primary">
            <a-icon type="plus"></a-icon>
            {{ __('lixir::system.btn.create') }}
        </a>
    </a-col>
</a-row>
<a-row type="flex" justify="center">
    <a-col :span="24">
        <property-table
            :properties="{{ $properties }}"
            inline-template
            base-url="{{ asset(config('lixir.admin_url')) }}">
            <a-table @change="handleTableChange" :columns="columns" row-key="id" :data-source="properties">
                <span slot="action" slot-scope="text, record">

                    <a :href="getEditUrl(record)">
                        <a-icon type="edit"></a-icon>
                    </a>
                    <a :href="getDeleteUrl(record)" v-on:click.prevent="deleteProperty(record)">
                        <a-icon type="delete"></a-icon>
                    </a>
                </span>
            </a-table>
        </property-tableinline-template>
    </a-col>
</a-row>
@endsection

resources/views/cms/page/create.blade.php
@extends('lixir::layouts.app')

@section('meta_title')
    {{ __('lixir::cms.page.create.title') }}: Lixir E-Commerce Admin Dashboard
@endsection

@section('page_title')
    {{ __('lixir::cms.page.create.title') }}
@endsection

@section('content')
<a-row type="flex" justify="center">
    <a-col :span="24">
        <page-save base-url="{{ asset(config('lixir.admin_url')) }}" inline-template>
        <div>
            <a-form
                :form="pageForm"
                method="post"
                action="{{ route('admin.page.store') }}"
                @submit="handleSubmit"
            >
                @csrf
                <a-tabs tabbar-gutter="15" tab-position="left" default-active-key="cms.page.info">
                @foreach ($tabs as $tab)
                    <a-tab-pane :force-render="true" tab="{{ $tab->label() }}" key="{{ $tab->key() }}">
                        @php
                            $path = $tab->view();
                        @endphp
                        @include($path)
                    </a-tab-pane>
                @endforeach
                </a-tabs>

                <a-form-item>
                    <a-button
                        type="primary"
                        html-type="submit"
                    >
                        {{ __('lixir::system.btn.save') }}
                    </a-button>

                    <a-button
                        class="ml-1"
                        type="default"
                        v-on:click.prevent="cancelPage"
                    >
                        {{ __('lixir::system.btn.cancel') }}
                    </a-button>
                </a-form-item>
            </a-form>
            </div>
        </page-save>
    </a-col>
</a-row>
@endsection

resources/views/cms/page/edit.blade.php
@extends('lixir::layouts.app')

@section('meta_title')
    {{ __('lixir::cms.page.edit.title') }}: Lixir E-Commerce Admin Dashboard
@endsection

@section('page_title')
    {{ __('lixir::cms.page.edit.title') }}
@endsection

@section('content')
<a-row type="flex" justify="center">
    <a-col :span="24">
        <page-save
            base-url="{{ asset(config('lixir.admin_url')) }}"
            :page="{{ $page }}" inline-template>
        <div>
            <a-form
                :form="pageForm"
                method="post"
                action="{{ route('admin.page.update', $page->id) }}"
                @submit="handleSubmit"
            >
                @csrf
                @method('put')
                <a-tabs tabbar-gutter="15" tab-position="left" default-active-key="cms.page.info">
                @foreach ($tabs as $tab)
                    <a-tab-pane :force-render="true" tab="{{ $tab->label() }}" key="{{ $tab->key() }}">
                        @php
                            $path = $tab->view();
                        @endphp
                        @include($path)
                    </a-tab-pane>
                @endforeach
                </a-tabs>

                <a-form-item>
                    <a-button
                        type="primary"
                        html-type="submit"
                    >
                        {{ __('lixir::system.btn.save') }}
                    </a-button>

                    <a-button
                        class="ml-1"
                        type="default"
                        v-on:click.prevent="cancelPage"
                    >
                        {{ __('lixir::system.btn.cancel') }}
                    </a-button>
                </a-form-item>
            </a-form>
            </div>
        </page-save>
    </a-col>
</a-row>
@endsection

resources/views/cms/page/index.blade.php
@extends('lixir::layouts.app')

@section('meta_title')
    {{ __('lixir::cms.page.index.title') }}: Lixir E-Commerce Admin Dashboard
@endsection

@section('page_title')
    {{ __('lixir::cms.page.index.title') }}
@endsection

@section('content')
<a-row type="flex" class="mb-1" justify="end">
    <a-col>
        <a
            href="{{ route('admin.page.create') }}"
            class="ant-btn ant-btn-primary">
            <a-icon type="plus"></a-icon>
            {{ __('lixir::system.btn.create') }}
        </a>
    </a-col>
</a-row>
<a-row type="flex" justify="center">
    <a-col :span="24">
        <page-table :pages="{{ $pages }}" inline-template base-url="{{ asset(config('lixir.admin_url')) }}">
            <a-table :columns="columns" row-key="id" :data-source="pages" @change="handleTableChange">
                <span slot="action" slot-scope="text, record">

                    <a :href="getEditUrl(record)">
                        <a-icon type="edit"></a-icon>
                    </a>
                    <a :href="getDeleteUrl(record)" v-on:click.prevent="deletePage(record)">
                        <a-icon type="delete"></a-icon>
                    </a>
                </span>
            </a-table>
        </page-table>
    </a-col>
</a-row>
@endsection

resources/views/system/configuration/index.blade.php
@extends('lixir::layouts.app')

@section('meta_title')
    Lixir E-Commerce Admin Dashboard
@endsection

@section('page_title')
    Configuration
@endsection

@section('content')
<a-row type="flex" justify="center">
    <a-col :span="24">
        <a-card :bordered="false" :style="{ padding: '16px 0', height: '100%' }" :style="{ height: '100%' }">
            <configuration-save base-url="{{ asset(config('lixir.admin_url')) }}"  inline-template>
            <a-form
                    :form="configurationForm"
                    method="post"
                    v-on:submit="handleSubmit"
                    action="{{ route('admin.configuration.store') }}">

                    @csrf

                    <a-tabs
                        default-active-key="system.configuration.basic"
                        tab-position="left">
                        @foreach ($tabs as $tab)
                            <a-tab-pane :force-render="true" tab="{{ $tab->label() }}" key="{{ $tab->key() }}">
                                @php
                                    $path = $tab->view();
                                @endphp
                                @include($path)
                            </a-tab-pane>
                        @endforeach
                    </a-tabs>

                    <a-form-item>
                        <a-button type="primary" html-type="submit">
                            {{ __('lixir::system.btn.save') }}
                        </a-button>

                        <a-button class="ml-1" type="default"v-on:click.prevent="cancelConfiguration">
                            {{ __('lixir::system.btn.cancel') }}
                        </a-button>
                    </a-form-item>

            </a-form>
            </configuration-save>
        </a-card>
    </a-col>
</a-row>
@endsection

resources/views/system/login/form.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('meta_title', 'Lixir E-Commerce')</title>

    <script defer src="{{ asset('lixir-admin/js/app.js') }}"></script>

    <!-- Styles -->
    <link href="{{ asset('lixir-admin/css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <login-fields loginpost="{{ route('admin.login.post') }}" inline-template>
            <div>
                <a-row type="flex" align="middle">
                    <a-col :span="12">
                        <a-row type="flex">
                        <a-col :span="20" :offset="2">
                            <a-card title="{{ __('lixir::system.login-card') }}">
                                <a-form
                                    :form="loginForm"
                                    method="post"
                                    action="{{ route('admin.login.post') }}"
                                    @submit="handleSubmit"
                                >
                                    @csrf()
                                    <a-form-item
                                        @if ($errors->has('email'))
                                            validate-status="error"
                                            help="{{ $errors->first('email') }}"
                                        @endif
                                        label="{{ __('lixir::system.email') }}">
                                    <a-input
                                        :auto-focus="true"
                                        name="email"
                                        v-decorator="[
                                        'email',
                                        {
                                            rules: [
                                                {   required: true,
                                                    message: '{{ __('lixir::validation.required', ['attribute' => 'email']) }}'
                                                }
                                            ]
                                        }
                                        ]"
                                    />
                                    </a-form-item>

                                    <a-form-item
                                        @if ($errors->has('password'))
                                            validate-status="error"
                                            help="{{ $errors->first('password') }}"
                                        @endif
                                        label="{{ __('lixir::system.password') }}">
                                        <a-input
                                            name="password"
                                            type="password"
                                            v-decorator="[
                                            'password',
                                            {rules: [{ required: true, message: '{{ __('lixir::validation.required', ['attribute' => 'password']) }}' }]}
                                            ]"
                                        />
                                    </a-form-item>

                                    <a-form-item>
                                        <a-button
                                            type="primary"
                                            :loading="loadingSubmitBtn"
                                            html-type="submit"
                                        >
                                            {{ __('lixir::system.login') }}
                                        </a-button>

                                        <a class="ml-1" href="{{ route('admin.password.request') }}">Forgot password?</a>
                                    </a-form-item>
                                </a-form>
                            </a-card>
                        </a-col>
                        </a-row>
                    </a-col>

                    <a-col :span="12">
                     <a-row type="flex" align="middle" class="h-100 text-center">
                      <a-col :span="24">
                            <img
                                class="height-100"
                                src="{{ asset('lixir-admin/images/octa_admin_login.svg')}}"
                                width="55%" alt="Lixir Admin Login" />
                        </a-col>
                        </a-row>
                    </a-col>
                </a-row>
            </div>

        </login-fields>
    </div>
    @stack('scripts')
</body>
</html>

resources/views/system/login/reset.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('meta_title', 'Lixir E-Commerce')</title>

    <script defer src="{{ asset('lixir-admin/js/app.js') }}"></script>

    <!-- Styles -->
    <link href="{{ asset('lixir-admin/css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <password-reset-page inline-template>
            <div>
                <a-row type="flex" align="middle">
                    <a-col :span="12">
                        <a-row type="flex">
                        <a-col :span="20" :offset="2">

                            <a-card title="{{ __('lixir::system.forgot-password-title') }}">
                                <a-form
                                    :form="form"
                                    method="post"
                                    action="{{ route('admin.password.email') }}"
                                    @submit="handleSubmit"
                                >
                                    @csrf()
                                    <a-form-item
                                        @if ($errors->has('email'))
                                            validate-status="error"
                                            help="{{ $errors->first('email') }}"
                                        @endif
                                        label="{{ __('lixir::system.email') }}">
                                    <a-input
                                        :auto-focus="true"
                                        name="email"
                                        v-decorator="[
                                        'email',
                                        {
                                            rules: [
                                                {   required: true,
                                                    message: '{{ __('lixir::validation.required', ['attribute' => 'email']) }}'
                                                }
                                            ]
                                        }
                                        ]"
                                    />
                                    </a-form-item>

                                    <a-form-item>
                                        <a-button
                                            type="primary"
                                            :loading="loadingSubmitBtn"
                                            html-type="submit"
                                        >
                                            {{ __('lixir::system.password-reset-btn') }}
                                        </a-button>

                                    </a-form-item>
                                </a-form>
                            </a-card>
                        </a-col>
                        </a-row>
                    </a-col>

                    <a-col :span="12">
                     <a-row type="flex" align="middle" class="h-100 text-center">
                      <a-col :span="24">
                            <img
                                class="height-100"
                                src="{{ asset('lixir-admin/images/octa_admin_login.svg')}}"
                                width="55%" alt="Lixir Admin Login" />
                        </a-col>
                        </a-row>
                    </a-col>
                </a-row>
            </div>

        </password-reset-page>
    </div>
    @stack('scripts')
</body>
</html>

resources/views/system/role/create.blade.php
@extends('lixir::layouts.app')


@section('meta_title')
    {{ __('lixir::system.role.create.title') }}: Lixir E-Commerce Admin Dashboard
@endsection

@section('page_title')
    {{ __('lixir::system.role.create.title') }}
@endsection

@section('content')
<a-row type="flex" justify="center">
    <a-col :span="24">
        <system-role-save base-url="{{ asset(config('lixir.admin_url')) }}" inline-template>
        <div>
            <a-form
                :form="roleForm"
                method="post"
                action="{{ route('admin.role.store') }}"
                @submit="handleSubmit"
            >
                @csrf

                <a-tabs tabbar-gutter="15" tab-position="left" default-active-key="system.role.info">
                @foreach ($tabs as $tab)
                    <a-tab-pane :force-render="true" tab="{{ $tab->label() }}" key="{{ $tab->key() }}">
                        @php
                            $path = $tab->view();
                        @endphp
                        @include($path)
                    </a-tab-pane>
                @endforeach
                </a-tabs>




                <a-form-item>
                    <a-button
                        type="primary"
                        html-type="submit">
                        {{ __('lixir::system.btn.save') }}
                    </a-button>

                    <a-button
                        class="ml-1"
                        type="default"
                        v-on:click.prevent="cancelRole"
                    >
                        {{ __('lixir::system.btn.cancel') }}
                    </a-button>

                </a-form-item>
            </a-form>
            </div>
        </system-role-save>
    </a-col>
</a-row>
@endsection

resources/views/system/role/edit.blade.php
@extends('lixir::layouts.app')

@section('meta_title')
    {{ __('lixir::system.role.edit.title') }}: Lixir E-Commerce Admin Dashboard
@endsection

@section('page_title')
    {{ __('lixir::system.role.edit.title') }}
@endsection

@section('content')
<a-row type="flex" justify="center">
    <a-col :span="24">
        <system-role-save
            base-url="{{ asset(config('lixir.admin_url')) }}"
            role="{{ $role }}" inline-template>
        <div>
            <a-form
                :form="roleForm"
                method="post"
                action="{{ route('admin.role.update', $role->id) }}"
                @submit="handleSubmit"
            >
                    @csrf
                    @method('put')

                    <a-tabs tabbar-gutter="15" tab-position="left" default-active-key="system.role.info">
                @foreach ($tabs as $tab)
                    <a-tab-pane :force-render="true" tab="{{ $tab->label() }}" key="{{ $tab->key() }}">
                        @php
                            $path = $tab->view();
                        @endphp
                        @include($path)
                    </a-tab-pane>
                @endforeach
                </a-tabs>


                <a-form-item>
                    <a-button
                        type="primary"
                        html-type="submit"
                    >
                        {{ __('lixir::system.btn.save') }}
                    </a-button>

                    <a-button
                        style="margin-left: 10px;"
                        type="default"
                        v-on:click.prevent="cancelRole"
                    >
                        {{ __('lixir::system.btn.cancel') }}
                    </a-button>
                </a-form-item>
            </a-form>
            </div>
        </system-role-save>
    </a-col>
</a-row>
@endsection

resources/views/system/role/index.blade.php
@extends('lixir::layouts.app')

@section('meta_title')
    {{ __('lixir::system.role.index.title') }}: Lixir E-Commerce Admin Dashboard
@endsection

@section('page_title')
    {{ __('lixir::system.role.index.title') }}
@endsection

@section('content')
<a-row type="flex" class="mb-1" justify="end">
    <a-col>
        <a
            href="{{ route('admin.role.create') }}"
            class="ant-btn ant-btn-primary">
            <a-icon type="plus"></a-icon>
            {{ __('lixir::system.btn.create') }}
        </a>
    </a-col>
</a-row>
<a-row type="flex" justify="center">
    <a-col :span="24">
        <role-index inline-template base-url="{{ asset(config('lixir.admin_url')) }}" :roles="{{ $roles }}">
            <a-table :columns="columns" row-key="id" @change="handleTableChange" :data-source="roles">
                <span slot="action" slot-scope="text, record">

                    <a :href="getEditUrl(record)">
                        <a-icon type="edit"></a-icon>
                    </a>
                    <a :href="getDeleteUrl(record)" v-on:click.prevent="deleteRole(record)">
                        <a-icon type="delete"></a-icon>
                    </a>
                </span>
            </a-table>
        </role-index>
    </a-col>
</a-row>
@endsection